# Generated by Django 5.2.15 on 2026-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_nickname_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="반려인 이름"
            ),
        ),
    ]
