# Generated by Django 5.2.15 on 2026-10-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('email_change', '이메일 변경'), ('password_reset', '비밀번호 재설정')], max_length=20),
        ),
    ]
