# Generated by Django 5.2.15 on 2026-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_pet_delete_dog"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="personalities",
            field=models.JSONField(blank=True, default=list, verbose_name="성격"),
        ),
    ]
