# Generated by Django 5.2.15 on 2026-08-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_personalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_level', models.PositiveIntegerField()),
                ('after_level', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_up_histories', to='pets.pet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
