# Generated by Django 5.2.15 on 2026-09-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="requester",
            new_name="user1",
        ),
        migrations.RenameField(
            model_name="friend",
            old_name="receiver",
            new_name="user2",
        ),
    ]