# Generated by Django 5.2.15 on 2026-09-28 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_rename_friend_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='friend',
            name='prevent_self_friend_request',
        ),
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friend_request',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.CheckConstraint(condition=models.Q(('user1_id__lt', models.F('user2_id'))), name='friend_user_order'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_friendship'),
        ),
    ]
