# Generated by Django 5.2.15 on 2026-09-29 05:54

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_options_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
