# Generated by Django 5.2.15 on 2026-08-01 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_pet_personalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='accessories/')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('DAILY', '일일'), ('WEEKLY', '주간')], max_length=10)),
                ('mission_type', models.CharField(choices=[('TOTAL_DISTANCE', '누적 산책 거리'), ('TOTAL_DURATION', '누적 산책 시간'), ('WALK_COUNT', '산책 완료 횟수'), ('WALK_DISTANCE_AT_LEAST', '일정 거리 이상 산책 횟수'), ('WALK_DURATION_AT_LEAST', '일정 시간 이상 산책 횟수'), ('DISTINCT_WALK_DAYS', '산책한 날짜 수'), ('NEW_FRIEND_COUNT', '새로 추가한 친구 수')], max_length=30)),
                ('goal', models.PositiveIntegerField(blank=True, null=True)),
                ('required_count', models.PositiveIntegerField(default=1)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('reward_accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_missions', to='missions.accessory')),
                ('reward_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_missions', to='missions.badge')),
            ],
        ),
        migrations.CreateModel(
            name='PetAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_accessories', to='missions.accessory')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_accessories', to='pets.pet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pet', 'accessory'), name='unique_pet_accessory')],
            },
        ),
        migrations.CreateModel(
            name='PetBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_badges', to='missions.badge')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_badges', to='pets.pet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pet', 'badge'), name='unique_pet_badge')],
            },
        ),
        migrations.CreateModel(
            name='PetMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행 중'), ('CLAIMABLE', '보상 수령 가능'), ('CLAIMED', '보상 수령 완료')], default='IN_PROGRESS', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_missions', to='missions.mission')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_missions', to='pets.pet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pet', 'mission', 'period_start'), name='unique_pet_mission_period')],
            },
        ),
    ]
