# Generated by Django 5.2.15 on 2026-08-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='reward_accessory',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='reward_badge',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='reward_experience',
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('HAIR', '헤어'), ('CAPE', '케이프'), ('CLOTHES', '옷'), ('SHOES', '신발')], default='HAIR', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('FIRST_FRIEND', '첫 친구 추가'), ('LEVEL', '레벨 달성'), ('RAINY_WALK', '비 오는 날 산책'), ('SNOWY_WALK', '눈 오는 날 산책'), ('TOTAL_DURATION', '누적 산책 시간'), ('TOTAL_DISTANCE', '누적 산책 거리'), ('FIRST_WALK', '첫 산책'), ('CONSECUTIVE_DAYS', '연속 산책 일수'), ('DAILY_WALK_COUNT', '하루 산책 횟수'), ('NEW_REGION', '새로운 지역 산책'), ('FOREST_WALK', '숲속 산책'), ('CITY_WALK', '도시 산책')], default='FIRST_WALK', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('TOTAL_DISTANCE', '누적 산책 거리'), ('TOTAL_DURATION', '누적 산책 시간'), ('WALK_COUNT', '산책 횟수'), ('WALK_DISTANCE_AT_LEAST', '1회 산책 거리'), ('WALK_DURATION_AT_LEAST', '1회 산책 시간'), ('DISTINCT_WALK_DAYS', '산책 일수'), ('NEW_FRIEND_COUNT', '새 친구 수')]),
        ),
        migrations.AlterField(
            model_name='mission',
            name='period',
            field=models.CharField(choices=[('DAILY', '일일'), ('WEEKLY', '주간')]),
        ),
    ]
