# Generated by Django 5.2.15 on 2026-08-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_remove_mission_reward_accessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
