# Generated by Django 5.2.15 on 2026-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_badge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('FIRST_FRIEND', '첫 친구 추가'), ('MAX_AFFECTION_FRIENDS', '최대 호감도 친구 수'), ('LEVEL', '레벨 달성'), ('RAINY_WALK', '비 오는 날 산책'), ('SNOWY_WALK', '눈 오는 날 산책'), ('TOTAL_DURATION', '누적 산책 시간'), ('TOTAL_DISTANCE', '누적 산책 거리'), ('FIRST_WALK', '첫 산책'), ('CONSECUTIVE_DAYS', '연속 산책 일수'), ('DAILY_WALK_COUNT', '하루 산책 횟수'), ('NEW_REGION', '새로운 지역 산책'), ('FOREST_WALK', '숲속 산책'), ('CITY_WALK', '도시 산책')], max_length=30),
        ),
    ]
