# Generated by Django 5.2.15 on 2026-07-26 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_delete_dog'),
        ('walk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkingsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='walkingsession',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walking_sessions', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='walkingpath',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='walkingpath',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='walkingsession',
            name='is_location_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='walkingsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='walking_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='walkingpath',
            index=models.Index(fields=['session', 'timestamp'], name='walk_walkin_session_58970e_idx'),
        ),
        migrations.AddIndex(
            model_name='walkingsession',
            index=models.Index(fields=['user', 'status'], name='walk_walkin_user_id_d5bf96_idx'),
        ),
        migrations.AddIndex(
            model_name='walkingsession',
            index=models.Index(fields=['user', '-start_time'], name='walk_walkin_user_id_813e87_idx'),
        ),
    ]
