# Generated by Django 5.2.15 on 2026-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walk", "0002_alter_walkingsession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingsession",
            name="last_paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
