# Generated by Django 5.2.15 on 2026-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0004_walkingpath_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkpreference',
            name='nearby_radius_km',
            field=models.FloatField(default=5.0),
        ),
    ]
