# Generated by Django 5.2.15 on 2026-10-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0005_walkpreference_nearby_radius_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenAreaTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('polygons', models.JSONField(default=list)),
                ('is_ok', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='walkingsession',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsession',
            name='is_city_walk',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsession',
            name='is_forest_walk',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkingsession',
            name='is_new_area',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VisitedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_key', models.CharField(max_length=32)),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_cells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'cell_key'), name='unique_user_visited_cell')],
            },
        ),
    ]
